### ISSUE TITLE
Typo 2.[shaper~].pd

### ISSUE THREAD

**Issue by chateaucarbone** [porres/Live-Electronic-Music-Tutorial#10]
Hi,

Just two typos int the patch "Vol.1-Essentials/Part.04-Synthesis(Basic)/20-Waveshaping/6.Chebyshev.polinomials/2.[shaper~].pd"

> The pacth below sends an enveloped sine trhough [shaper~]

should be : "patch" and "through".

Best.

**Comment by porres** [comment]
thanks I bet there are a milllion typos and grammar errors :)
